from sqlalchemy import create_engine
from sqlalchemy.exc import ProgrammingError
import os
import pandas as pd
from sqlalchemy import MetaData
from sqlalchemy import Table

curr_dir = os.path.dirname(os.path.realpath(__file__))
data_path = os.path.join(curr_dir, 'data')

mapped_data_path = os.path.join(data_path, 'mapped_data.xlsx')
df_mapped_data = pd.read_excel(mapped_data_path)


class Base:

    def __init__(self):
        self.BASEDIR = os.path.abspath(os.path.dirname(__file__))
        self.USERNAME = "postgres"
        self.PASSWORD = "admin"
        self.PORT = 5432
        self.DB_NAME = "CollegeCardDB"
        self.POSTGRES_LOCAL_BASE = "postgresql://{username}:{password}@localhost:{port}/{db_name}".format(username=self.USERNAME,
                                                                                                     password=self.PASSWORD,
                                                                                                     port=self.PORT,
                                                                                                     db_name=self.DB_NAME)

        self.engine = create_engine(self.POSTGRES_LOCAL_BASE)
        self.conn = self.engine.connect()


class Users(Base):

    def __init__(self):
        super().__init__()
        id = "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        first_name = "first_name VARCHAR(255)"
        last_name = "last_name VARCHAR(255)"
        email = "email VARCHAR(255)"
        username = "username VARCHAR(255) UNIQUE"
        dob = "dob DATE"
        joined_site = "joined_site DATE"
        password = "password VARCHAR(255)"
        educational_attainment = "educational_attainment VARCHAR(255)"
        try:
            self.conn.execute("CREATE TABLE Users({id},"
                              "{first_name}, "
                              "{last_name}, "
                              "{username},"
                              "{email},"
                              "{dob},"
                              "{joined_site},"
                              "{password},"
                              "{educational_attainment}"");".format(id=id,
                                                                    first_name=first_name,
                                                                    last_name=last_name,
                                                                    email=email,
                                                                    username=username,
                                                                    dob=dob,
                                                                    joined_site=joined_site,
                                                                    password=password,
                                                                    educational_attainment=educational_attainment))
        except ProgrammingError as error:
            print('TABLE ALREADY EXISTS')

        except:
            print("SOMETHING ELSE WENT TERRIBLY WRONG")

    def add_dummy_users(self):
        file_path = os.path.join(data_path, 'users.csv')
        df = pd.read_csv(file_path)
        with open(file_path, 'r') as f:
            connection = self.engine.raw_connection()
            cursor = connection.cursor()
            cmd = 'COPY users(dob,educational_attainment,email,first_name,joined_site,last_name,password,username) FROM STDIN WITH (FORMAT CSV, HEADER TRUE)'
            cursor.copy_expert(cmd, f)
            connection.commit()

    def insert_user(self, first_name, last_name, username, email, dob, joined_site, password, educational_attainment):
        self.conn.execute("INSERT INTO users(first_name, last_name, username, dob, joined_site, password, "
                          "educational_attainment) "
                          "VALUES ("
                          "'{first_name}',"
                          "'{last_name}',"
                          "'{username}',"
                          "'{email}',"
                          "'{dob}',"
                          "'{joined_site}',"
                          "'{password}',"
                          "'{educational_attainment}')".format(first_name=first_name,
                                                               last_name=last_name,
                                                               username=username,
                                                               email=email,
                                                               dob=dob,
                                                               joined_site=joined_site,
                                                               password=password,
                                                               educational_attainment=educational_attainment))


class Comments(Base):

    def __init__(self):
        super().__init__()
        id = "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        user_id = "user_id integer"
        comment = "comment VARCHAR(255)"

        try:
            self.conn.execute("CREATE TABLE comments({id}, {user_id}, {comment});".format(id=id,
                                                                                           user_id=user_id,
                                                                                           comment=comment))
        except ProgrammingError:
            print('TABLE ALREADY EXISTS')

    def insert_comment(self,):
        self.conn.execute("INSERT INTO comments(user_id, comment) VALUES ('02', 'comment')")


users = Users()
users.add_dummy_users()